import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { UploadCloud, FileText, Lock } from "lucide-react";
import { LanguageText } from "@/components/language-context";

export function SupportingFilesPanel() {
    return (
        <Card>
            <CardHeader>
                <CardTitle>
                    <LanguageText en="Supporting Engineering References" zh="支持性工程资料" />
                </CardTitle>
            </CardHeader>
            <CardContent>
                <div className="border-2 border-dashed border-slate-200 rounded-lg p-8 flex flex-col items-center justify-center bg-slate-50 text-slate-500 hover:bg-slate-100 transition-colors cursor-pointer">
                    <UploadCloud className="w-8 h-8 mb-3 text-slate-400" />
                    <p className="font-medium text-sm">
                        <LanguageText en="Drag & drop files here, or click to select" zh="拖放文件至此，或点击选择" />
                    </p>
                    <p className="text-xs text-muted-foreground mt-1">
                        <LanguageText 
                            en="Recommended: CAD (STEP/IGES), Review PDF, Test Data (CSV)" 
                            zh="推荐: CAD (STEP/IGES), 评审 PDF, 测试数据 (CSV)" 
                        />
                    </p>
                </div>
                
                {/* Mock Uploaded File */}
                <div className="mt-4 space-y-2">
                    <div className="flex items-center justify-between p-3 bg-white border rounded-md shadow-sm">
                        <div className="flex items-center gap-3">
                            <div className="bg-blue-100 text-blue-600 p-2 rounded">
                                <FileText className="w-4 h-4" />
                            </div>
                            <div>
                                <div className="text-sm font-medium">engineering_review_v1.pdf</div>
                                <div className="text-xs text-muted-foreground">
                                    <LanguageText en="Generated by ISRI-SHUANGDI System" zh="由 ISRI-SHUANGDI 系统生成" />
                                </div>
                            </div>
                        </div>
                        <Lock className="w-4 h-4 text-slate-300" />
                    </div>
                </div>
            </CardContent>
        </Card>
    );
}
